<a href="https://colab.research.google.com/github/romiaprilian7406/tutorial-numpy/blob/main/tutorial_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Version

In [ ]:
import numpy as np

print(f"numpy version: {np.__version__}")

numpy version: 2.0.2


# Ndarray

In [ ]:
import numpy as np

# 1D (Vektor)
arr_1d = np.array([1, 2, 3])
print(f"arr_1d: {arr_1d}")
print(f"ndim: {arr_1d.ndim}")
print(f"shape: {arr_1d.shape}\n")

# 2D (Matriks)
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
print(f"arr_2d: \n{arr_2d}")
print(f"ndim: {arr_2d.ndim}")
print(f"shape: {arr_2d.shape}\n")

# 3D (Tensor)
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"arr_3d: \n{arr_3d}")
print(f"ndim: {arr_3d.ndim}")
print(f"shape: {arr_3d.shape}\n")

# specify minimum dimension
arr_ndmin = np.array([1, 2, 3, 4, 5], ndmin=3)
print(f"arr_ndmin: \n{arr_ndmin}\n")

# specify data type
arr_dtype = np.array([1, 2, 3, 4, 5], dtype=np.float32)
print(f"arr_dtype: \n{arr_dtype}\n")

arr_1d: [1 2 3]
ndim: 1
shape: (3,)

arr_2d: 
[[1 2]
 [3 4]
 [5 6]]
ndim: 2
shape: (3, 2)

arr_3d: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
ndim: 3
shape: (2, 2, 3)

arr_ndmin: 
[[[1 2 3 4 5]]]

arr_dtype: 
[1. 2. 3. 4. 5.]



# Data Types
Data Types & Description
1. bool_ : Boolean (True or False) stored as a byte

2. int_ : Default integer type (same as C long; normally either int64 or int32)

3. intc : Identical to C int (normally int32 or int64)

4. intp : Integer used for indexing (same as C ssize_t; normally either int32 or int64)

5. int8 : Byte (-128 to 127)

6. int16 : Integer (-32768 to 32767)

7. int32 : Integer (-2147483648 to 2147483647)

8. int64 : Integer (-9223372036854775808 to 9223372036854775807)

9. uint8 : Unsigned integer (0 to 255)

10. uint16 : Unsigned integer (0 to 65535)

11. uint32 : Unsigned integer (0 to 4294967295)

12. uint64 : Unsigned integer (0 to 18446744073709551615)

13. float_ : Shorthand for float64

14. float16 : Half precision float: sign bit, 5 bits exponent, 10 bits mantissa

15. float32 : Single precision float: sign bit, 8 bits exponent, 23 bits mantissa

16. float64 : Double precision float: sign bit, 11 bits exponent, 52 bits mantissa

17. complex_ : Shorthand for complex128

18. complex64 : Complex number, represented by two 32-bit floats (real and imaginary components)

19. complex128 : Complex number, represented by two 64-bit floats (real and imaginary components)

In [ ]:
import numpy as np

# Create Arrays With Defined Data Type
arr_dt = np.array([1, 2, 3], dtype=np.int64)
print(f"arr_dt: \n{arr_dt}")
print(f"dtype: {arr_dt.dtype}\n")

# Convert Data Type of NumPy Arrays
# Metode astype membuat salinan array dan mengonversinya ke tipe data yang ditentukan. Ini adalah metode yang paling sering digunakan untuk mengubah tipe data array.
arr_cdt = arr_dt.astype(np.float32)
print(f"arr_cdt: \n{arr_cdt}")
print(f"dtype: {arr_cdt.dtype}\n")

arr_dt: 
[1 2 3]
dtype: int64

arr_cdt: 
[1. 2. 3.]
dtype: float32



# Creating and Manipulating

## Cretion Routines
numpy.array() Function

numpy.zeros() Function

numpy.ones() Function

numpy.arange() Function

numpy.linspace() Function

numpy.random.rand() Function

numpy.empty() Function

numpy.full() Function

### zeros

In [ ]:
import numpy as np

arr_zeros1d = np.zeros(4)
print(f"arr_zeros1d: \n{arr_zeros1d}\n")

arr_zeros2d = np.zeros([2,3])
print(f"arr_zeros2d: \n{arr_zeros2d}\n")

arr_zeros3d = np.zeros([2,3,4])
print(f"arr_zeros3d: \n{arr_zeros3d}\n")

arr_zeros1d: 
[0. 0. 0. 0.]

arr_zeros2d: 
[[0. 0. 0.]
 [0. 0. 0.]]

arr_zeros3d: 
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]



### ones

In [ ]:
import numpy as np

arr_ones1d = np.ones(4)
print(f"arr_ones1d: \n{arr_ones1d}\n")

arr_ones2d = np.ones([2,3])
print(f"arr_ones2d: \n{arr_ones2d}\n")

arr_ones3d = np.ones([2,3,4])
print(f"arr_ones3d: \n{arr_ones3d}\n")

arr_ones1d: 
[1. 1. 1. 1.]

arr_ones2d: 
[[1. 1. 1.]
 [1. 1. 1.]]

arr_ones3d: 
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]



In [ ]:
import numpy as np

# 1D
arr_1 = np.arange(10)
print(f"arr_1: \n{arr_1}\n")
arr_2 = np.arange(5, 10)
print(f"arr_2: \n{arr_2}\n")
arr_3 = np.arange(10, 0, -1)
print(f"arr_3: \n{arr_3}\n")

# 2D
arr2 = np.arange(6).reshape(2,3)
print(f"arr2: \n{arr2}\n")

# 3D
arr3 = np.arange(10, -2, -1, dtype=np.float32).reshape(3,2,2) # 3 blok, 2 baris, 2 kolom
print(f"arr3: \n{arr3}\n")
print(f"dtype (before): {arr3.dtype}\n")

arr3_2 = arr3.astype(np.int8)
print(f"arr3_2: \n{arr3_2}\n")
print(f"dtype (after): {arr3_2.dtype}\n")

arr_

arr_1: 
[0 1 2 3 4 5 6 7 8 9]

arr_2: 
[5 6 7 8 9]

arr_3: 
[10  9  8  7  6  5  4  3  2  1]

arr2: 
[[0 1 2]
 [3 4 5]]

arr3: 
[[[10.  9.]
  [ 8.  7.]]

 [[ 6.  5.]
  [ 4.  3.]]

 [[ 2.  1.]
  [ 0. -1.]]]

dtype (before): float32

arr3_2: 
[[[10  9]
  [ 8  7]]

 [[ 6  5]
  [ 4  3]]

 [[ 2  1]
  [ 0 -1]]]

dtype (after): int8


### linspace

In [ ]:
# numpy.linspace : Fungsi untuk membuat array dengan jumlah titik tertentu yang merata jaraknya antara nilai awal dan akhir.
# Beda dengan np.arange (yang pakai step), np.linspace pakai jumlah titik.

# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
# start → nilai awal
# stop → nilai akhir
# num → jumlah titik (default = 50)
# endpoint → kalau True, stop disertakan; kalau False, titik terakhir < stop
# retstep → kalau True, juga mengembalikan jarak antar titik (step)
# dtype → tipe data

# arange(start, stop, step) → tentukan jarak antar titik (step), jumlah titik ditentukan otomatis.
# linspace(start, stop, num) → tentukan jumlah titik, jaraknya otomatis dihitung.

import numpy as np

# 1D
# 5 titik merata dari 0 sampai 1.
arr_1 = np.linspace(0, 1, 5)
print(f"arr_1: \n{arr_1}\n")

# Masih 5 titik, tapi 1 tidak dimasukkan.
arr_2 = np.linspace(0, 1, 5, endpoint=False)
print(f"arr_2: \n{arr_2}\n")

# Jarak antar titik = 0.25
arr_3, step = np.linspace(0, 1, 5, retstep=True)
print(f"arr_3: \n{arr_3}\n")

# 2D
arr2 = np.linspace(0, 1, 6).reshape(3, 2)
print(f"arr2: \n{arr2}\n")

# 3D
arr3 = np.linspace(0, 1, 18).reshape(3, 2, 3)
print(f"arr2: \n{arr3}\n")

arr_1: 
[0.   0.25 0.5  0.75 1.  ]

arr_2: 
[0.  0.2 0.4 0.6 0.8]

arr_3: 
[0.   0.25 0.5  0.75 1.  ]

arr2: 
[[0.  0.2]
 [0.4 0.6]
 [0.8 1. ]]

arr2: 
[[[0.         0.05882353 0.11764706]
  [0.17647059 0.23529412 0.29411765]]

 [[0.35294118 0.41176471 0.47058824]
  [0.52941176 0.58823529 0.64705882]]

 [[0.70588235 0.76470588 0.82352941]
  [0.88235294 0.94117647 1.        ]]]

