<a href="https://colab.research.google.com/github/romiaprilian7406/tutorial-numpy/blob/main/tutorial_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Version

In [2]:
import numpy as np

print(f"numpy version: {np.__version__}")

numpy version: 2.0.2


# Ndarray

In [4]:
# 1D (Vektor)
arr_1d = np.array([1, 2, 3])
print(f"arr_1d: {arr_1d}")
print(f"ndim: {arr_1d.ndim}")
print(f"shape: {arr_1d.shape}\n")

# 2D (Matriks)
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
print(f"arr_2d: \n{arr_2d}")
print(f"ndim: {arr_2d.ndim}")
print(f"shape: {arr_2d.shape}\n")

# 3D (Tensor)
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"arr_3d: \n{arr_3d}")
print(f"ndim: {arr_3d.ndim}")
print(f"shape: {arr_3d.shape}\n")

# specify minimum dimension
arr_ndmin = np.array([1, 2, 3, 4, 5], ndmin=3)
print(f"arr_ndmin: \n{arr_ndmin}\n")

# specify data type
arr_dtype = np.array([1, 2, 3, 4, 5], dtype=np.float32)
print(f"arr_dtype: \n{arr_dtype}\n")

arr_1d: [1 2 3]
ndim: 1
shape: (3,)

arr_2d: 
[[1 2]
 [3 4]
 [5 6]]
ndim: 2
shape: (3, 2)

arr_3d: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
ndim: 3
shape: (2, 2, 3)

arr_ndmin: 
[[[1 2 3 4 5]]]

arr_dtype: 
[1. 2. 3. 4. 5.]



# Data Types
Data Types & Description
1. bool_ : Boolean (True or False) stored as a byte

2. int_ : Default integer type (same as C long; normally either int64 or int32)

3. intc : Identical to C int (normally int32 or int64)

4. intp : Integer used for indexing (same as C ssize_t; normally either int32 or int64)

5. int8 : Byte (-128 to 127)

6. int16 : Integer (-32768 to 32767)

7. int32 : Integer (-2147483648 to 2147483647)

8. int64 : Integer (-9223372036854775808 to 9223372036854775807)

9. uint8 : Unsigned integer (0 to 255)

10. uint16 : Unsigned integer (0 to 65535)

11. uint32 : Unsigned integer (0 to 4294967295)

12. uint64 : Unsigned integer (0 to 18446744073709551615)

13. float_ : Shorthand for float64

14. float16 : Half precision float: sign bit, 5 bits exponent, 10 bits mantissa

15. float32 : Single precision float: sign bit, 8 bits exponent, 23 bits mantissa

16. float64 : Double precision float: sign bit, 11 bits exponent, 52 bits mantissa

17. complex_ : Shorthand for complex128

18. complex64 : Complex number, represented by two 32-bit floats (real and imaginary components)

19. complex128 : Complex number, represented by two 64-bit floats (real and imaginary components)

In [ ]:
# Create Arrays With Defined Data Type
arr_dt = np.array([1, 2, 3], dtype=np.int64)
print(f"arr_dt: \n{arr_dt}")
print(f"dtype: {arr_dt.dtype}\n")

# Convert Data Type of NumPy Arrays
# Metode astype membuat salinan array dan mengonversinya ke tipe data yang ditentukan. Ini adalah metode yang paling sering digunakan untuk mengubah tipe data array.
arr_cdt = arr_dt.astype(np.float32)
print(f"arr_cdt: \n{arr_cdt}")
print(f"dtype: {arr_cdt.dtype}\n")

arr_dt: 
[1 2 3]
dtype: int64

arr_cdt: 
[1. 2. 3.]
dtype: float32



# axis

In [ ]:
# along different rows (baris)
# along different columns (kolom)

# 1D
# axis : 0 -> vektor

# 2D
# axis : 0 -> baris
# axis : 1 -> kolom

# 3D
# axis : 0 -> along different 2D arrays
# axis : 1 -> along different rows in each 2D arrays
# axis : 2 -> along different columns in each 2D arrays

# 4D
# axis : 0 -> along different 3D arrays
# axis : 1 -> along different 2D arrays in each 3D arrays
# axis : 2 -> along different rows in each 2D arrays
# axis : 3 -> along different columns in each 2D arrays

# 5D
# axis : 0 -> along different 4D arrays
# axis : 1 -> along different 3D arrays in each 4D arrays
# axis : 2 -> along different 2D arrays in each 3D arrays
# axis : 3 -> along different rows in each 2D arrays
# axis : 4 -> along different columns in each 2D arrays

# 1D
a = np.array([1,2,3,4,5])
print(f"a: {a}")
a_sum_a0 = np.sum(a, axis=0)
print(f"a_sum_a0: {a_sum_a0}\n")

# 2D
x = np.array(
    [[1, 2, 3],
    [10, 20, 30],]
)

x_sum = np.sum(x)
print(f"x: \n{x}")
print(f"x_sum: {x_sum}")

# axis = 0 (baris)
x_sum_a0 = np.sum(x, axis=0)
print(f"x_sum_a0: {x_sum_a0}")

# axis = 1 (kolom)
x_sum_a1 = np.sum(x, axis=1)
print(f"x_sum_a1: {x_sum_a1}\n")

# 3D
y = np.array(
    [[[1,2],
      [3,4]],

     [[5,6],
     [7,8]]]
)
print(f"y: \n{y}\n")

y_sum_a0 = np.sum(y, axis=0) # matriks
print(f"y_sum_a0: \n{y_sum_a0}\n")

y_sum_a1 = np.sum(y, axis=1) # baris
print(f"y_sum_a1: \n{y_sum_a1}\n")

y_sum_a2 = np.sum(y, axis=2) # kolom
print(f"y_sum_a2: \n{y_sum_a2}")

a: [1 2 3 4 5]
a_sum_a0: 15

x: 
[[ 1  2  3]
 [10 20 30]]
x_sum: 66
x_sum_a0: [11 22 33]
x_sum_a1: [ 6 60]

y: 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

y_sum_a0: 
[[ 6  8]
 [10 12]]

y_sum_a1: 
[[ 4  6]
 [12 14]]

y_sum_a2: 
[[ 3  7]
 [11 15]]


# copies vs views

copy
generates a new array and copies the data from the original array into this new array. When you create a copy of an array in NumPy, the data is fully duplicated. This means that changes made to the copy do not affect the original array, and vice versa. Copies are useful when you need to work with a modified version of an array without altering the original data.

1. Buat array baru di memori.
2. Data asli tidak terhubung.
3. Perubahan di copy tidak memengaruhi array asli.

shallow copy (view)
A shallow copy of an array creates a new array object, but it does not create copies of the elements contained within the original array if those elements themselves are arrays or other complex objects.Instead, the new array still references the same elements as the original array. This means that changes to the contents of the elements will affect both the original and the copied array.

1. Hanya salin metadata array (shape, strides, dtype), bukan datanya.
2. Kedua array menunjuk ke buffer memori yang sama.
3. Perubahan di satu array terlihat di lainnya.



---


Operasi                 View / Copy

Slicing (a[2:5])	         View

Reshape (jika mungkin)	   View

Transpose .T	             View

Ravel (kadang)	           View

Fancy indexing [ [0,2] ]	 Copy

Boolean indexing	         Copy

.copy()	                   Copy

astype()	                 Copy

np.array(..., copy=True)	 Copy

np.asarray(...)	           View (jika bisa)


---


.base : Mengecek apakah sebuah array copy atau view
1. Kalau arr.base is None → berarti array asli.
2. Kalau arr.base menunjuk ke array lain → berarti view dari array itu.

In [12]:


# ====== copy ======
# original
arr_og1 = np.array([1,2,3])

# copy
arr_copied1 = arr_og1.copy()
arr_copied1[1] = 10

print(f"arr_og1: {arr_og1}")
print(f"arr_og1.base: {arr_og1.base}")
print(f"arr_copied1: {arr_copied1}")
print(f"arr_copied1.base: {arr_copied1.base}\n")

# ====== Shallow copy (view) ======
# Original array
arr_og2 = np.array([[1, 2, 3], [4, 5, 6]])

# Shallow copy
arr_view2 = arr_og2.view()

# Modify an element in the shallow copy
arr_view2[0, 0] = 100
print(f"arr_og2: \n{arr_og2}")
print(f"arr_og2.base: {arr_og2.base}")
print(f"arr_view2: \n{arr_view2}")
print(f"arr_view2.base: \n{arr_view2.base}\n")

# ======
# original
arr_og3 = np.array(
    [[1,2,3],
     [4,5,6]]
)
arr_copied3 = arr_og3.copy()
arr_copied3[1,2] = 99
print(f"arr_og3: \n{arr_og3}")
print(f"arr_og3.base: \n{arr_og3.base}")
print(f"arr_copied3: \n{arr_copied3}")
print(f"arr_copied3.base: \n{arr_copied3.base}\n")

# ====== Copying Subarrays ======
arr_og4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Creating a copy of the subarray
sub_array = arr_og4[0:2].copy()
sub_array[0] = 20
print(f"arr_og4: \n{arr_og4}")
print(f"sub_array: \n{sub_array}\n")

# ====== Creating Views ======
# Original array
arr_og5 = np.array([1, 2, 3])

arr_view5 = arr_og5[0:2]

# Modifying the view
arr_view5[0] = 30
print(f"arr_og5: \n{arr_og5}")
print(f"arr_view5: \n{arr_view5}\n")

# === VIEWS FROM SLICING ===
# Original array
arr_og6 = np.array([1, 2, 3, 4, 5])

# Creating a view by slicing the original array
arr_view6 = arr_og6[1:4]
print(f"arr_og6: \n{arr_og6}")
print(f"arr_view6: \n{arr_view6}\n")

# === VIEWS FROM RESHAPING ===
# Original 1D array
arr_og7 = np.array([1, 2, 3, 4, 5, 6])

# Reshaping the array into a 2x3 matrix
arr_view7 = arr_og7.reshape(2, 3)
print(f"arr_og7: \n{arr_og7}")
print(f"arr_view7: \n{arr_view7}\n")

# === VIEWS FROM RESHAPING ===
# Original 2D array
arr_og8 = np.array([[1, 2, 3], [4, 5, 6]])

# Transposing the array
arr_view8 = arr_og8.T
print(f"arr_og8: \n{arr_og8}")
print(f"arr_view8: \n{arr_view8}\n")

arr_og1: [1 2 3]
arr_og1.base: None
arr_copied1: [ 1 10  3]
arr_copied1.base: None

arr_og2: 
[[100   2   3]
 [  4   5   6]]
arr_og2.base: None
arr_view2: 
[[100   2   3]
 [  4   5   6]]
arr_view2.base: 
[[100   2   3]
 [  4   5   6]]

arr_og3: 
[[1 2 3]
 [4 5 6]]
arr_og3.base: 
None
arr_copied3: 
[[ 1  2  3]
 [ 4  5 99]]
arr_copied3.base: 
None

arr_og4: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
sub_array: 
[[20 20 20]
 [ 4  5  6]]

arr_og5: 
[30  2  3]
arr_view5: 
[30  2]

arr_og6: 
[1 2 3 4 5]
arr_view6: 
[2 3 4]

arr_og7: 
[1 2 3 4 5 6]
arr_view7: 
[[1 2 3]
 [4 5 6]]

arr_og8: 
[[1 2 3]
 [4 5 6]]
arr_view8: 
[[1 4]
 [2 5]
 [3 6]]



# np.array() vs np.asarray()
| Fitur                 | `np.array()`                               | `np.asarray()`                                       |
| --------------------- | ------------------------------------------ | ---------------------------------------------------- |
| **Input list/tuple**  | Buat array baru                            | Buat array baru                                      |
| **Input NumPy array** | **Selalu copy** (kecuali `copy=False`)     | **Tidak copy** (hanya view jika dtype & order cocok) |
| **Kontrol copy**      | Bisa atur dengan argumen `copy=True/False` | Tidak ada argumen `copy` (default = hemat)           |
| **Efisiensi**         | Bisa lebih boros memori (karena copy)      | Lebih hemat, cepat (hindari copy jika tidak perlu)   |
| **Use case utama**    | Kalau butuh array baru yang terpisah       | Kalau hanya ingin “pastikan” input jadi array NumPy  |


---

np.asarray(obj) :

Kalau obj sudah ndarray dan dtype/order sama → kembalikan objek yang sama.

Kalau tidak → bikin copy dengan dtype/order baru.

np.array(obj) :

Selalu bikin array baru (copy) kecuali kamu eksplisit pakai copy=False.

In [20]:
# ===== From List/Tuple Python =====
x = [1,2,3,4,5]

# np.array()
arr_1 = np.array(x)

# np.asarray()
arr_2 = np.asarray(x)

x[2] = 99

print(f"x: {x}")
print(f"arr_1: {arr_1}, x is arr_1: {x is arr_1}")
print(f"arr_2: {arr_2}, x is arr_2: {x is arr_2}\n")

# ===== From Numpy Array (same dtype) =====
y = np.array([100,200,300,400,500])

# np.array()
arr_3 = np.array(y)

# np.asarray()
arr_4 = np.asarray(y)

y[2] = 0

print(f"y: {y}")
print(f"arr_3: {arr_3}, y is arr_3: {y is arr_3}")
print(f"arr_4: {arr_4}, y is arr_4 {y is arr_4}\n")

# ===== From Numpy Array (diff dtype) =====
z = np.array([1, 2, 3], dtype=np.int32)
arr_5 = np.array(z, dtype=np.float32)
arr_6 = np.asarray(z)
print(f"z: {z}")
print(f"arr_5: {arr_5}, z is arr_5: {z is arr_5}")
print(f"arr_6: {arr_6}, z is arr_6 {z is arr_6}\n")



x: [1, 2, 99, 4, 5]
arr_1: [1 2 3 4 5], x is arr_1: False
arr_2: [1 2 3 4 5], x is arr_2: False

y: [100 200   0 400 500]
arr_3: [100 200 300 400 500], y is arr_3: False
arr_4: [100 200   0 400 500], y is arr_4 True

z: [1 2 3]
arr_5: [1. 2. 3.], z is arr_5: False
arr_6: [1 2 3], z is arr_6 True



# Creating and Manipulating

## Array Cretion Routines
numpy.array() Function

numpy.zeros() Function

numpy.ones() Function

numpy.arange() Function

numpy.linspace() Function

numpy.random.rand() Function

numpy.empty() Function

numpy.full() Function

### zeros

In [ ]:
arr_zeros1d = np.zeros(4)
print(f"arr_zeros1d: \n{arr_zeros1d}\n")

arr_zeros2d = np.zeros([2,3])
print(f"arr_zeros2d: \n{arr_zeros2d}\n")

arr_zeros3d = np.zeros([2,3,4])
print(f"arr_zeros3d: \n{arr_zeros3d}\n")

arr_zeros1d: 
[0. 0. 0. 0.]

arr_zeros2d: 
[[0. 0. 0.]
 [0. 0. 0.]]

arr_zeros3d: 
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]



### ones

In [ ]:
arr_ones1d = np.ones(4)
print(f"arr_ones1d: \n{arr_ones1d}\n")

arr_ones2d = np.ones([2,3])
print(f"arr_ones2d: \n{arr_ones2d}\n")

arr_ones3d = np.ones([2,3,4])
print(f"arr_ones3d: \n{arr_ones3d}\n")

arr_ones1d: 
[1. 1. 1. 1.]

arr_ones2d: 
[[1. 1. 1.]
 [1. 1. 1.]]

arr_ones3d: 
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]



### arange

In [ ]:
# 1D
arr_1 = np.arange(10)
print(f"arr_1: \n{arr_1}\n")
arr_2 = np.arange(5, 10)
print(f"arr_2: \n{arr_2}\n")
arr_3 = np.arange(10, 0, -1)
print(f"arr_3: \n{arr_3}\n")

# 2D
arr2 = np.arange(6).reshape(2,3)
print(f"arr2: \n{arr2}\n")

# 3D
arr3 = np.arange(10, -2, -1, dtype=np.float32).reshape(3,2,2) # 3 blok, 2 baris, 2 kolom
print(f"arr3: \n{arr3}\n")
print(f"dtype (before): {arr3.dtype}\n")

arr3_2 = arr3.astype(np.int8)
print(f"arr3_2: \n{arr3_2}\n")
print(f"dtype (after): {arr3_2.dtype}\n")

arr_1: 
[0 1 2 3 4 5 6 7 8 9]

arr_2: 
[5 6 7 8 9]

arr_3: 
[10  9  8  7  6  5  4  3  2  1]

arr2: 
[[0 1 2]
 [3 4 5]]

arr3: 
[[[10.  9.]
  [ 8.  7.]]

 [[ 6.  5.]
  [ 4.  3.]]

 [[ 2.  1.]
  [ 0. -1.]]]

dtype (before): float32

arr3_2: 
[[[10  9]
  [ 8  7]]

 [[ 6  5]
  [ 4  3]]

 [[ 2  1]
  [ 0 -1]]]

dtype (after): int8



### linspace

In [ ]:
# numpy.linspace : Fungsi untuk membuat array dengan jumlah titik tertentu yang merata jaraknya antara nilai awal dan akhir.
# Beda dengan np.arange (yang pakai step), np.linspace pakai jumlah titik.

# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
# start → nilai awal
# stop → nilai akhir
# num → jumlah titik (default = 50)
# endpoint → kalau True, stop disertakan; kalau False, titik terakhir < stop
# retstep → kalau True, juga mengembalikan jarak antar titik (step)
# dtype → tipe data

# arange(start, stop, step) → tentukan jarak antar titik (step), jumlah titik ditentukan otomatis.
# linspace(start, stop, num) → tentukan jumlah titik, jaraknya otomatis dihitung.

# 1D
# 5 titik merata dari 0 sampai 1.
arr_1 = np.linspace(0, 1, 5)
print(f"arr_1: \n{arr_1}\n")

# Masih 5 titik, tapi 1 tidak dimasukkan.
arr_2 = np.linspace(0, 1, 5, endpoint=False)
print(f"arr_2: \n{arr_2}\n")

# Jarak antar titik = 0.25
arr_3, step = np.linspace(0, 1, 5, retstep=True)
print(f"arr_3: \n{arr_3}\n")

# 2D
arr2 = np.linspace(0, 1, 6).reshape(3, 2)
print(f"arr2: \n{arr2}\n")

# 3D
arr3 = np.linspace(0, 1, 18).reshape(3, 2, 3)
print(f"arr2: \n{arr3}\n")

arr_1: 
[0.   0.25 0.5  0.75 1.  ]

arr_2: 
[0.  0.2 0.4 0.6 0.8]

arr_3: 
[0.   0.25 0.5  0.75 1.  ]

arr2: 
[[0.  0.2]
 [0.4 0.6]
 [0.8 1. ]]

arr2: 
[[[0.         0.05882353 0.11764706]
  [0.17647059 0.23529412 0.29411765]]

 [[0.35294118 0.41176471 0.47058824]
  [0.52941176 0.58823529 0.64705882]]

 [[0.70588235 0.76470588 0.82352941]
  [0.88235294 0.94117647 1.        ]]]



### empty

In [ ]:
# np.empty(): Fungsi untuk membuat array baru dengan ukuran tertentu. Isinya tidak diinisialisasi → artinya nilai di dalam array bisa berupa angka acak “sampah” yang sudah ada di memori. Sangat cepat karena NumPy tidak repot mengisi elemen.

# Kapan menggunakan : Kalau kamu langsung akan mengisi array dengan nilai baru (misalnya lewat loop atau operasi). Supaya lebih efisien dan hemat waktu dibanding zeros. np.empty() aman dipakai kalau kamu langsung isi array dengan nilai baru. Kalau butuh nilai awal yang jelas (0, 1, atau random acak), sebaiknya jangan pakai ini.

# np.zeros(shape)
# → buat array dengan semua elemen 0. Lebih aman kalau butuh nilai awal jelas.Lebih lambat daripada empty() karena harus isi semua dengan nol.

# np.ones(shape)
# → buat array dengan semua elemen 1.

# np.full(shape, fill_value)
# → buat array dengan nilai tertentu.

# np.empty(shape)
# → buat array kosong, isinya tidak ditentukan.Lebih cepat.Cocok kalau nanti langsung menimpa semua elemen (misalnya lewat perhitungan).

arr_e1 = np.empty((4,))
print(f"arr_e1: \n{arr_e1}\n")

arr_e2 = np.empty((2,3), dtype=np.float32)
print(f"arr_e2: \n{arr_e2}\n")

arr_e3 = np.empty((2,3,4), dtype=np.int8)
print(f"arr_e3: \n{arr_e3}\n")

arr_e1: 
[2.75443222e-315 0.00000000e+000 4.94065646e-324 6.54254384e-310]

arr_e2: 
[[6.3298792e-19 0.0000000e+00 1.4012985e-45]
 [0.0000000e+00 2.8608226e-34 4.3204834e-41]]

arr_e3: 
[[[ 55 -45  58  33]
  [  0   0   0   0]
  [  1   0   0   0]]

 [[  0   0   0   0]
  [ 96  34 -66   7]
  [112 120   0   0]]]



### full

In [ ]:
arr_f1 = np.full(2,5, dtype=np.complex64)
print(f"arr_f1: \n{arr_f1}\n")

arr_f2 = np.full((3,2), False, dtype=bool)
print(f"arr_f2: \n{arr_f2}\n")

arr_f3 = np.full((2,4,3), True, dtype=bool)
print(f"arr_f3: \n{arr_f3}\n")

arr_f1: 
[5.+0.j 5.+0.j]

arr_f2: 
[[False False]
 [False False]
 [False False]]

arr_f3: 
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]]



## iterating

### Loop

In [9]:
# 1D
arr_1d = np.array([1,2,3,4])
for i in arr_1d:
  print(i)

print()

# 2D
arr_2d = np.array(
    [[100, 200],
     [300, 400]]
)
# 1
for row in arr_2d:
  print(row)
# 2
for row in arr_2d:
  for item in row:
    print(item)

print()

# 3D
arr_3d = np.array(
    [[[1,2],
      [3,4]],

     [[5,6],
     [7,8]]]
)
# 1
for mat in arr_3d:
  print(mat)

# 2
for mat in arr_3d:
  for row in mat:
    for item in row:
      print(item)


1
2
3
4

[100 200]
[300 400]
100
200
300
400

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
1
2
3
4
5
6
7
8


### nditer

In [13]:
# 1D
arr_1d = np.array([1,2,3,4])
for i in np.nditer(arr_1d):
  print(i)

print()

# 2D
arr_2d = np.array(
    [[100, 200],
     [300, 400]]
)
for i in np.nditer(arr_2d):
  print(i)

print()

# 3D
arr_3d = np.array(
    [[[1,2],
      [3,4]],

     [[5,6],
     [7,8]]]
)
for i in np.nditer(arr_3d):
  print(i)

1
2
3
4

100
200
300
400

1
2
3
4
5
6
7
8


### ndenumerate

In [19]:
# 1D
arr_1d = np.array([1,2,3,4])
for idx, item in np.ndenumerate(arr_1d):
  print(idx, item)

print()

# 2D
arr_2d = np.array(
    [[100, 200],
     [300, 400]]
)
for idx, item in np.ndenumerate(arr_2d):
  print(idx, item)

print()

# 3D
arr_3d = np.array(
    [[[1,2],
      [3,4]],

     [[5,6],
     [7,8]]]
)
for idx, item in np.ndenumerate(arr_3d):
  print(idx, item)

(0,) 1
(1,) 2
(2,) 3
(3,) 4

(0, 0) 100
(0, 1) 200
(1, 0) 300
(1, 1) 400

7
(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


In [20]:
image = np.arange(3*3*3).reshape(3,3,3)  # 3x3 pixel, 3 channel
print(image)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


## reshape

In [27]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a_2d = a.reshape(4,3)
a_3d = a.reshape(3,2,2)
print(f"a:\n{a}\n")
print(f"a_2d:\n{a_2d}\n")
print(f"a_3d:\n{a_3d}\n")

b = np.arange(12).reshape(3, -1) # 3 baris, kolom dihitung otomatis
print(f"b:\n{b}\n")

c = np.arange(12).reshape(-1, 3) # 3 kolom, baris dihitung otomatis
print(f"c:\n{c}\n")

d = np.arange(18).reshape(3, -1, 2)
print(f"d:\n{d}\n")


a:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

a_2d:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

a_3d:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

c:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

d:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]



## concatenate
Concatenate
Menyambung array di dimensi yang sudah ada.
Tidak menambah dimensi baru.
👉 Bayangkan ada dua tali 👉 disambung jadi satu tali panjang.

Stack
Menggabungkan array dengan cara menambah dimensi baru.
Beda dengan concatenate, karena hasilnya punya 1 dimensi ekstra.
👉 Bayangkan dua kertas 👉 ditumpuk jadi setumpuk kertas (ada “ketebalan”).


---


Concatenate → sambung di dimensi lama.

Stack → tambah dimensi baru.


---


Concatenate = menyambung jalan → lebih panjang tapi tetap 1 jalur.

Stack = membangun lantai baru → tambah arah vertikal.

In [37]:
# 1D
arr1d_1 = np.array([1,2,3])
arr1d_2 = np.array([4,5,6])
arr_con1d = np.concatenate((arr1d_1, arr1d_2))
print(f"arr_con1d: {arr_con1d}\n")

# 2D
arr2d_1 = np.array(
    [[1,2],
     [3,4]]
)
arr2d_2 = np.array(
    [[5,6],
     [7,8]]
)
arr_con2d = np.concatenate((arr2d_1, arr2d_2))
print(f"arr_con2d:\n{arr_con2d}")

# 3D

arr_con1d: [1 2 3 4 5 6]

arr_con2d:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## stacking

### stack

In [44]:
# 1D
arr1d_1 = np.array([1, 2, 3])
arr1d_2 = np.array([4, 5, 6])
arr1d_3 = np.array([7, 8, 9])

# Stack arrays along a new axis
stacked_arr_a0 = np.stack((arr1d_1, arr1d_2, arr1d_3), axis=0)
print(f"stacked_arr_a0:\n{stacked_arr_a0}")

stacked_arr_a1 = np.stack((arr1d_1, arr1d_2, arr1d_3), axis=1)
print(f"stacked_arr_a1:\n{stacked_arr_a1}")

# 2D



stacked_arr_a0:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
stacked_arr_a1:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
